CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "accounts_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "name" varchar(100) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "accounts_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "accounts_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "accounts_user_groups_user_id_group_id_59c0b32f_uniq" ON "accounts_user_groups" ("user_id", "group_id");
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
CREATE UNIQUE INDEX "accounts_user_user_permissions_user_id_permission_id_2ab516c2_uniq" ON "accounts_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "medicos_especialidade" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(200) NOT NULL);
CREATE TABLE IF NOT EXISTS "medicos_medico" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(200) NOT NULL, "email" varchar(254) NOT NULL, "crp" varchar(200) NOT NULL, "telefone" varchar(17) NULL, "especialidade_id" bigint NOT NULL REFERENCES "medicos_especialidade" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "medicos_agenda" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dia" date NOT NULL, "horario" varchar(10) NOT NULL, "medico_id" bigint NOT NULL REFERENCES "medicos_medico" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "medicos_medico_especialidade_id_d5ffd7e5" ON "medicos_medico" ("especialidade_id");
CREATE UNIQUE INDEX "medicos_agenda_horario_dia_d17f539e_uniq" ON "medicos_agenda" ("horario", "dia");
CREATE INDEX "medicos_agenda_medico_id_850a527a" ON "medicos_agenda" ("medico_id");
CREATE INDEX "medicos_agenda_user_id_5efb6d0f" ON "medicos_agenda" ("user_id");
CREATE TABLE IF NOT EXISTS "clientes_cliente" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sexo" varchar(9) NOT NULL, "telefone" varchar(17) NULL, "cpf" varchar(50) NOT NULL UNIQUE, "user_id" bigint NOT NULL UNIQUE REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "clientes_consulta" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "agenda_id" bigint NOT NULL UNIQUE REFERENCES "medicos_agenda" ("id") DEFERRABLE INITIALLY DEFERRED, "cliente_id" bigint NOT NULL REFERENCES "clientes_cliente" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "clientes_consulta_agenda_id_cliente_id_1934ecf6_uniq" ON "clientes_consulta" ("agenda_id", "cliente_id");
CREATE INDEX "clientes_consulta_cliente_id_ee8b9aeb" ON "clientes_consulta" ("cliente_id");
CREATE TABLE IF NOT EXISTS "clientes_file_upload" ("ids" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file_name" varchar(255) NOT NULL, "my_file" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "clientes_file_upload2" ("ids" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file_name" varchar(255) NOT NULL, "my_file2" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "clientes_myfile2" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "arq" varchar(100) NOT NULL, "title" varchar(255) NULL);
CREATE TABLE IF NOT EXISTS "clientes_myfile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NULL, "arq" varchar(100) NOT NULL);
