# Generated by Django 4.0.1 on 2023-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_myfile_arq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='arq',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
