# Generated by Django 4.0.1 on 2023-11-16 16:05

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_myfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='arq',
            field=models.FileField(upload_to=clientes.models.get_upload_path),
        ),
    ]
