# Generated by Django 4.0.1 on 2023-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_myfile_arq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
