# Generated by Django 4.0.1 on 2023-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_myfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload2',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('my_file2', models.FileField(upload_to='')),
            ],
        ),
    ]
