# Generated by Django 4.0.1 on 2023-11-16 19:37

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_file_upload2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.FileField(upload_to=clientes.models.get_upload_path)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
