# Generated by Django 4.0.1 on 2023-11-16 20:26

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_myfile_destination_folder_alter_myfile_arq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='arq',
            field=models.FileField(upload_to=clientes.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
