# Generated by Django 4.0.1 on 2023-11-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_myfile_arq_alter_myfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='destination_folder',
        ),
    ]
